# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import unittest

import dtool_lookup_openapi_client
from dtool_lookup_openapi_client.model.register_user import RegisterUser


class TestRegisterUser(unittest.TestCase):
    """RegisterUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_RegisterUser(self):
        """Test RegisterUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RegisterUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
