# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import unittest

import dtool_lookup_openapi_client
from dtool_lookup_openapi_client.model.uri_permission import UriPermission


class TestUriPermission(unittest.TestCase):
    """UriPermission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_UriPermission(self):
        """Test UriPermission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UriPermission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
