# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from dtool_lookup_openapi_client.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class PaginationMetadata(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    total = IntSchema
    total_pages = IntSchema
    first_page = IntSchema
    last_page = IntSchema
    page = IntSchema
    previous_page = IntSchema
    next_page = IntSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        total: typing.Union[total, Unset] = unset,
        total_pages: typing.Union[total_pages, Unset] = unset,
        first_page: typing.Union[first_page, Unset] = unset,
        last_page: typing.Union[last_page, Unset] = unset,
        page: typing.Union[page, Unset] = unset,
        previous_page: typing.Union[previous_page, Unset] = unset,
        next_page: typing.Union[next_page, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'PaginationMetadata':
        return super().__new__(
            cls,
            *args,
            total=total,
            total_pages=total_pages,
            first_page=first_page,
            last_page=last_page,
            page=page,
            previous_page=previous_page,
            next_page=next_page,
            _configuration=_configuration,
            **kwargs,
        )
