# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from dtool_lookup_openapi_client.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class Summary(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    
    
    class datasets_per_tag(
        DictSchema
    ):
        _additional_properties = IntSchema
    
    
        def __new__(
            cls,
            *args: typing.Union[dict, frozendict, ],
            _configuration: typing.Optional[Configuration] = None,
            **kwargs: typing.Type[Schema],
        ) -> 'datasets_per_tag':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
                **kwargs,
            )
    
    
    class tags(
        ListSchema
    ):
        _items = StrSchema
    number_of_datasets = IntSchema
    
    
    class base_uris(
        ListSchema
    ):
        _items = StrSchema
    
    
    class datasets_per_creator(
        DictSchema
    ):
        _additional_properties = IntSchema
    
    
        def __new__(
            cls,
            *args: typing.Union[dict, frozendict, ],
            _configuration: typing.Optional[Configuration] = None,
            **kwargs: typing.Type[Schema],
        ) -> 'datasets_per_creator':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
                **kwargs,
            )
    
    
    class datasets_per_base_uri(
        DictSchema
    ):
        _additional_properties = IntSchema
    
    
        def __new__(
            cls,
            *args: typing.Union[dict, frozendict, ],
            _configuration: typing.Optional[Configuration] = None,
            **kwargs: typing.Type[Schema],
        ) -> 'datasets_per_base_uri':
            return super().__new__(
                cls,
                *args,
                _configuration=_configuration,
                **kwargs,
            )
    
    
    class creator_usernames(
        ListSchema
    ):
        _items = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        datasets_per_tag: typing.Union[datasets_per_tag, Unset] = unset,
        tags: typing.Union[tags, Unset] = unset,
        number_of_datasets: typing.Union[number_of_datasets, Unset] = unset,
        base_uris: typing.Union[base_uris, Unset] = unset,
        datasets_per_creator: typing.Union[datasets_per_creator, Unset] = unset,
        datasets_per_base_uri: typing.Union[datasets_per_base_uri, Unset] = unset,
        creator_usernames: typing.Union[creator_usernames, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'Summary':
        return super().__new__(
            cls,
            *args,
            datasets_per_tag=datasets_per_tag,
            tags=tags,
            number_of_datasets=number_of_datasets,
            base_uris=base_uris,
            datasets_per_creator=datasets_per_creator,
            datasets_per_base_uri=datasets_per_base_uri,
            creator_usernames=creator_usernames,
            _configuration=_configuration,
            **kwargs,
        )
