# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from dtool_lookup_openapi_client.api_client import ApiClient
from dtool_lookup_openapi_client.api.mongo_api_endpoints.mongo_aggregate_post import MongoAggregatePost
from dtool_lookup_openapi_client.api.mongo_api_endpoints.mongo_config_get import MongoConfigGet
from dtool_lookup_openapi_client.api.mongo_api_endpoints.mongo_query_post import MongoQueryPost


class MongoApi(
    MongoAggregatePost,
    MongoConfigGet,
    MongoQueryPost,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
