# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from dtool_lookup_openapi_client.api_client import ApiClient
from dtool_lookup_openapi_client.api.permissions_api_endpoints.admin_permission_info_post import AdminPermissionInfoPost
from dtool_lookup_openapi_client.api.permissions_api_endpoints.admin_permission_update_on_base_uri_post import AdminPermissionUpdateOnBaseUriPost


class PermissionsApi(
    AdminPermissionInfoPost,
    AdminPermissionUpdateOnBaseUriPost,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
