# coding: utf-8

"""
    dtool-lookup-server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""

from dtool_lookup_openapi_client.api_client import ApiClient
from dtool_lookup_openapi_client.api.webhook_api_endpoints.webhook_config_get import WebhookConfigGet
from dtool_lookup_openapi_client.api.webhook_api_endpoints.webhook_notify_path_post import WebhookNotifyPathPost
from dtool_lookup_openapi_client.api.webhook_api_endpoints.webhook_notify_post import WebhookNotifyPost


class WebhookApi(
    WebhookConfigGet,
    WebhookNotifyPathPost,
    WebhookNotifyPost,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
